Code for NLP Multilabel Classification

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import nltk
import re
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
# Binary Relevance
from sklearn.multiclass import OneVsRestClassifier
# Performance metric
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
# Models
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
#
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk import pos_tag

In [ ]:
nltk.download()

In [ ]:
df = pd.read_csv('/content/NEW_TRAIN.csv (1).xls')
df['name'] = df['name']+" " + df['document_text']
df.drop(['id','document_text','cat_name'], inplace = True, axis = 1)
df.head()

,Unnamed: 0,name,Corporate Communications,Securities Settlement,Antitrust,Financial Crime,Commodities Trading,Examinations,Insurance,Required Disclosures,...,Accounting and Finance,Fraud,Broker Dealer,Securities Issuing,Risk Management,Forms,Definitions,Liquidity Risk,Money Services,Research
0,0,Information Regarding the Merger of Navios Mar...,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,Announcement on Approving the Change of Member...,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,SFC Suspends Shiu Yau Wah for Five Months The ...,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,"Renminbi RMB Haircut - February 4, 2020 Pursua...",0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,"Anti-Money Laundering, Countering Financing of...",0,0,0,1,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0

In [ ]:
df.drop('Unnamed: 0',axis = 1, inplace=True)

In [ ]:
stop_words = set(stopwords.words('english')) #creating a set of stop words
stop_words

In [ ]:
stop_words = set(stopwords.words('english')) #creating a set of stop words
def cleanResume(resumeText):
  
    resumeText=resumeText.lower()
    # resumeText = re.sub('http\S+\s*', ' ', resumeText)  # remove URLs
    # resumeText = re.sub('#\S+', '', resumeText)  # remove hashtags
    resumeText = re.sub('[%s]' % re.escape("""!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~"""), ' ', resumeText)  # remove punctuations
    resumeText = re.sub(r'\d*',r'', resumeText)  
    resumeText = re.sub('\s+', ' ', resumeText)
    word_tokens = word_tokenize(resumeText)
    filtered_sentence = [w for w in word_tokens if not w in stop_words] #Contains words other than stop words
    # tagged_corpus=pos_tag(filtered_sentence)
    # tagged_corpus_list=[prat_lemmatize(token, tag) for token, tag in tagged_corpus]
    resumeText=' '.join(filtered_sentence)
    return resumeText

In [ ]:
df['name'] = df.name.apply(lambda x: cleanResume(x))

In [ ]:
y=df.drop(columns=["name"], axis=1)

In [ ]:
df.columns

Index(['name', 'Corporate Communications', 'Securities Settlement',
       'Antitrust', 'Financial Crime', 'Commodities Trading', 'Examinations',
       'Insurance', 'Required Disclosures', 'Consumer protection',
       'Market Risk', 'Natural Disasters', 'Securities Management',
       'Information Filing', 'Quotation', 'Financial Accounting',
       'Securities Clearing', 'Listing', 'Records Maintenance', 'Delivery',
       'Monetary and Economic Policy', 'Banking', 'Regulatory Actions',
       'Securities Sales', 'Compliance Management', 'Fees and Charges',
       'Licensing', 'Legal Proceedings', 'Corporate Governance', 'Exemptions',
       'Legal', 'Contract Provisions', 'Payments and Settlements', 'IT Risk',
       'Trade Pricing', 'Licensure and certification', 'Trade Settlement',
       'Market Abuse', 'Regulatory Reporting', 'Powers and Duties',
       'Money-Laundering and Terrorist Financing', 'Accounting and Finance',
       'Fraud', 'Broker Dealer', 'Securities Issuing', 'Risk Management',
       'Forms', 'Definitions', 'Liquidity Risk', 'Money Services', 'Research'],
      dtype='object')

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df['name'], y)

In [ ]:
vectorizer = TfidfVectorizer(max_df=0.9, max_features=8000,ngram_range= (1, 2))
X_train_transformed = vectorizer.fit_transform(X_train)
X_test_transformed = vectorizer.transform(X_test)

In [ ]:
from joblib import dump, load
dump(vectorizer, 'vectorizer.pkl')

['vectorizer.pkl']

In [ ]:
y_train

,Corporate Communications,Securities Settlement,Antitrust,Financial Crime,Commodities Trading,Examinations,Insurance,Required Disclosures,Consumer protection,Market Risk,...,Accounting and Finance,Fraud,Broker Dealer,Securities Issuing,Risk Management,Forms,Definitions,Liquidity Risk,Money Services,Research
5636,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4238,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4622,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
6193,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7662,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,1,0,0,0,0,0
14,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3852,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7406,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
697,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
import lightgbm as lgb
lgbm = lgb.LGBMClassifier()
model = OneVsRestClassifier(lgbm)
model.fit(X_train_transformed, y_train)

In [ ]:
import pickle
pickle.dump(model, open('/content/drive/MyDrive/DATASOLVE/model.pkl', 'wb'))

In [ ]:
from sklearn.metrics import f1_score

In [ ]:
predictions= model.predict(X_test_transformed)
f1_score(y_test, predictions, average="macro")

In [ ]:
f1_score(y_test, predictions, average="macro")

In [ ]:
testing=pd.read_csv("/content/drive/MyDrive/test.csv")

In [ ]:
testing['name'] = testing['name']+" " + testing['document_text']

In [ ]:
testing['name'] = testing.name.apply(lambda x: cleanResume(x))

In [ ]:
test_x_tfidf = vectorizer.transform(testing['name'])
y_test_pred = model.predict(test_x_tfidf)

In [ ]:
y_test_pred

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
ans = pd.DataFrame(y_test_pred, columns = y.columns)
ans.head()

,Corporate Communications,Securities Settlement,Antitrust,Financial Crime,Commodities Trading,Examinations,Insurance,Required Disclosures,Consumer protection,Market Risk,...,Accounting and Finance,Fraud,Broker Dealer,Securities Issuing,Risk Management,Forms,Definitions,Liquidity Risk,Money Services,Research
0,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
import pickle

def predFunc(name, text):
  concat=name+text
  cleaned=cleanResume(concat)
  transformed=vectorizer.transform([cleaned])
  pred=model.predict(transformed)
  ans = pd.DataFrame(pred, columns = y.columns)
  
  l=ans.columns
  empty_list=[]
  for i, rows in ans.iterrows():
    for j in l:
      if rows[j]==1:
        empty_list.append(j)

  
  return empty_list

In [ ]:
name="Renminbi RMB Haircut - February 4, 2020"
text="Pursuant to Section 2.6.2 of the Clearing House Procedures of HKFE Clearing Corporation Limited (HKCC) and Section 10.4.3.1 of the Operational Clearing Procedures of The SEHK Options Clearing House Limited (SEOCH), the Clearing Houses have determined to adjust the haircut on RMB deposited as margin collateral from 3.1% to 3.5% after the close of business on 7 February 2020. The haircut shall be applied on a daily basis to determine the value of any RMB allowed to be used as a cover for the margin requirements of HKCC and/or SEOCH participants for contracts with settlement currency prescribed in HKD or USD. Participants should make necessary funding arrangements to cover any shortfall to their margin requirements resulting from the adjustment of the RMB haircut."
print(predFunc(name,text))

['Securities Settlement', 'Securities Clearing', 'Payments and Settlements', 'Trade Settlement']